import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Theme>{children}</Theme>
        </StoreProvider>
      </body>
    </html>
  );
}
